// Each entry is "<emoji> <words>". Add your own family favourites to any list!

const WHO = [
  // people
  "👵 grandma", "👴 grandad", "👨‍🦳 old man", "👩‍🦳 old lady", "👶 baby", "🧒 little kid", "👦 cheeky boy", "👧 girl with pigtails",
  "👨 dad", "👩 mum", "🧑‍🍼 big sister", "🧔 bearded man", "👱 teenager", "🤵 groom", "👰 bride", "🧑‍🎓 student",
  "🧑‍🏫 teacher", "🧑‍⚕️ doctor", "🦷 dentist", "🧑‍🍳 chef", "🧑‍🌾 farmer", "🧑‍🚒 firefighter", "👮 police officer", "🧑‍✈️ pilot",
  "🧑‍🚀 astronaut", "🕵️ detective", "🧑‍🎤 rock star", "💃 dancer", "🤹 juggler", "🤡 clown", "🎩 magician", "🏋️ strongman",
  "🥷 ninja", "🤺 knight", "🏴‍☠️ pirate", "🤠 cowboy", "👑 king", "👸 queen", "🤴 prince", "👸 princess",
  "🦸 superhero", "🦹 villain", "🧙 wizard", "🧙‍♀️ witch", "🧚 fairy", "🧜 mermaid", "🧝 elf", "🧞 genie",
  "🎅 Santa", "🧛 vampire", "🧟 zombie", "👻 ghost", "💀 skeleton", "👽 alien", "🤖 robot", "👾 space monster",
  "🧌 troll", "👹 friendly ogre", "🧸 teddy bear", "🪆 wooden doll", "🥋 karate kid", "🧑‍🔧 plumber", "🚴 cyclist", "🏊 swimmer",
  "⛷️ skier", "🏄 surfer", "🧑‍🎨 painter", "📸 photographer", "🎻 violinist", "🚌 bus driver", "🧑‍🚀 spaceman", "🕺 disco dancer",
  // animals
  "🐑 sheep", "🐮 cow", "🐷 pig", "🐴 horse", "🐓 chicken", "🐥 baby chick", "🦆 duck", "🦢 swan",
  "🦃 turkey", "🐐 goat", "🐶 puppy", "🐕 sausage dog", "🐩 poodle", "🐱 kitten", "🐈 fat cat", "🐭 mouse",
  "🐹 hamster", "🐰 bunny", "🦊 fox", "🐻 bear", "🐻‍❄️ polar bear", "🐼 panda", "🐨 koala", "🦁 lion",
  "🐯 tiger", "🐆 leopard", "🐘 elephant", "🦒 giraffe", "🦓 zebra", "🦛 hippo", "🦏 rhino", "🦘 kangaroo",
  "🐒 monkey", "🦍 gorilla", "🐧 penguin", "🦉 owl", "🦜 parrot", "🦩 flamingo", "🦚 peacock", "🕊️ pigeon",
  "🦅 eagle", "🐦 little bird", "🐸 frog", "🐢 tortoise", "🐍 snake", "🐊 crocodile", "🦎 lizard", "🐌 snail",
  "🐛 caterpillar", "🦋 butterfly", "🐝 bee", "🐞 ladybird", "🕷️ spider", "🐜 ant", "🦗 cricket", "🪰 fly",
  "🦀 crab", "🦞 lobster", "🐙 octopus", "🦑 squid", "🐠 goldfish", "🐡 pufferfish", "🦈 shark", "🐳 whale",
  "🐬 dolphin", "🦭 seal", "🦥 sloth", "🦔 hedgehog", "🦦 otter", "🦡 badger", "🐿️ squirrel", "🦇 bat",
  "🐪 camel", "🦙 llama", "🐺 wolf", "🦝 raccoon", "🦌 deer", "🦬 bison", "🐗 warthog", "🐀 rat",
  "🪱 worm", "🦫 beaver", "🦤 dodo", "🦨 skunk", "🐃 buffalo", "🦄 unicorn", "🐉 dragon", "🐲 baby dragon",
  "🦖 T-rex", "🦕 long-necked dinosaur", "🐴 pony", "🐎 racehorse", "🐕‍🦺 guide dog", "🐇 white rabbit", "🦢 ugly duckling", "🐈‍⬛ black cat",
  // silly
  "🍌 dancing banana", "🍕 pizza with legs", "🥕 carrot man", "🍄 mushroom person", "⛄ snowman", "🍪 gingerbread man", "🌽 corn on legs", "🍑 wiggly bum",
  "💨 smelly fart cloud", "🧦 sock puppet", "🥚 egg with a face", "🍦 melting ice cream", "🌻 sunflower with a smile", "☁️ grumpy cloud", "🌞 happy sun", "⭐ sleepy star"
];

const PLACES = [
  "🏠 kitchen", "🛋️ living room", "🛏️ bedroom", "🛁 bathroom", "🪑 writing desk", "🏡 garden shed", "🧺 laundry basket", "🪜 attic",
  "🕳️ cellar", "🚪 under the stairs", "🧊 inside the fridge", "🍽️ dinner table", "🛒 supermarket", "🧁 bakery", "🍦 ice cream van", "🥐 café",
  "🏫 classroom", "📚 library", "🏥 hospital", "🦷 dentist's chair", "💈 barbershop", "👗 clothes shop", "🧸 toy shop", "🎪 circus",
  "🎠 fairground", "🎡 top of a Ferris wheel", "🎢 rollercoaster", "🏟️ football stadium", "🏊 swimming pool", "⛸️ ice rink", "🎳 bowling alley", "⛳ crazy golf course",
  "🏖️ beach", "🏝️ desert island", "🌊 middle of the ocean", "🐠 coral reef", "🚤 speedboat", "🛶 canoe", "⛵ pirate ship", "🚢 cruise ship",
  "🌲 forest", "🏕️ campsite", "⛺ tent", "🏔️ mountain top", "🌋 volcano", "🏜️ desert", "🌴 jungle", "🌾 farmyard",
  "🐄 cow field", "🐑 sheep pen", "🐓 hen house", "🍎 apple orchard", "🌻 sunflower field", "🌷 flower bed", "🌉 bridge", "🏞️ waterfall",
  "🚏 bus stop", "🚌 school bus", "🚂 steam train", "🚇 underground station", "✈️ aeroplane", "🛫 airport", "🚁 helicopter", "🚀 rocket ship",
  "🌙 the moon", "🪐 Saturn's rings", "🛸 flying saucer", "👽 alien planet", "🌍 outer space", "☁️ on a cloud", "🌈 end of the rainbow", "⛅ in the sky",
  "🏰 castle", "🏯 haunted house", "🕌 magic palace", "🗼 tall tower", "🗽 big statue", "🏛️ museum", "🎭 theatre stage", "🎬 film set",
  "🧛 spooky graveyard", "🕸️ cobweb corner", "🦇 bat cave", "🐉 dragon's lair", "🧙 wizard's tower", "🧚 fairy ring", "🍄 giant mushroom", "🌳 treehouse",
  "⛲ park fountain", "🛝 playground slide", "🎠 roundabout", "🤸 trampoline", "🏰 bouncy castle", "🪂 parachute", "🛹 skate park", "🚴 bike path",
  "🏗️ building site", "🚒 fire station", "🚓 police station", "📮 post office", "🏦 bank vault", "🏨 hotel lobby", "🛗 lift", "🪟 window ledge",
  "🧼 car wash", "⛽ petrol station", "🚗 traffic jam", "🛣️ motorway", "🅿️ car park", "🚜 tractor", "🚛 lorry", "🛻 pickup truck",
  "🍕 pizza restaurant", "🍣 sushi bar", "🍔 burger joint", "🥘 school canteen", "🍰 birthday party", "🎄 Christmas tree", "🎃 pumpkin patch", "🎆 fireworks display",
  "🎅 Santa's workshop", "🦌 North Pole", "⛄ snowy hill", "🧊 igloo", "🏂 ski slope", "🛷 sledging hill", "🐧 Antarctica", "🧊 iceberg",
  "🎤 karaoke stage", "🎸 rock concert", "🎹 piano", "🥁 drum kit", "📺 inside the TV", "🎮 video game", "📖 inside a storybook", "🖼️ inside a painting",
  "🛒 shopping trolley", "🧺 picnic blanket", "🛌 bunk bed", "🪣 sandpit", "🌊 paddling pool", "🚿 shower", "🚽 toilet", "🛁 bubble bath",
  "🏖️ sandcastle", "🪸 shipwreck", "🏴‍☠️ treasure island", "🗺️ treasure cave", "🕳️ rabbit hole", "🐘 elephant's back", "🐪 camel's hump", "🦒 giraffe's neck",
  "🐋 inside a whale", "🐙 octopus's garden", "🌵 cactus patch", "🌽 cornfield maze", "🧩 giant maze", "🚧 roadworks", "🏚️ old shed", "🧱 brick wall",
  "🏠 on the roof", "🔥 campfire", "🕯️ candlelit room", "🌃 city at night", "🌆 rooftop", "🌅 sunset", "🌌 under the stars", "🌧️ in the rain",
  "🌪️ tornado", "🌬️ windy hilltop", "⛈️ thunderstorm", "🏜️ quicksand", "🕳️ giant hole", "🌀 whirlpool", "🛟 lifeboat", "⚓ harbour",
  "🧑‍🍳 restaurant kitchen", "👨‍🔬 science lab", "🛰️ space station", "🏫 headteacher's office", "🪑 naughty step", "🛏️ messy bedroom", "🧦 sock drawer", "🧥 wardrobe"
];

const ACTIONS = [
  "✍️ writing", "🎨 painting", "🖍️ colouring in", "📖 reading", "🎤 singing", "💃 dancing", "🕺 breakdancing", "🤸 doing cartwheels",
  "🤹 juggling", "🏃 running", "🐌 crawling slowly", "🚶 tiptoeing", "🛌 sleepwalking", "😴 snoring", "🥱 yawning", "🤧 sneezing",
  "🤭 giggling", "😂 laughing", "😭 crying", "😱 screaming", "🤢 feeling sick", "🤮 burping", "💨 farting", "🙈 hiding",
  "🫣 peeking", "🕵️ spying", "🔍 searching", "🧭 getting lost", "🪂 parachuting", "🪁 flying a kite", "✈️ flying", "🚀 blasting off",
  "🏊 swimming", "🤿 diving", "🏄 surfing", "🚣 rowing", "⛵ sailing", "🎣 fishing", "🏄 paddleboarding", "⛷️ skiing",
  "🏂 snowboarding", "⛸️ ice skating", "🛹 skateboarding", "🚴 cycling", "🛴 scootering", "🏇 horse riding", "🐘 riding an elephant", "🦄 riding a unicorn",
  "🧗 climbing", "🤾 throwing", "🥎 catching", "⚽ kicking", "🏀 dribbling", "🎾 serving", "🏓 playing ping pong", "🏌️ playing golf",
  "🥊 boxing", "🤼 wrestling", "🤺 sword fighting", "🏹 shooting arrows", "🎯 throwing darts", "🎳 bowling", "🏋️ lifting weights", "🧘 doing yoga",
  "🍳 cooking", "🥞 flipping pancakes", "🍰 baking", "🍕 eating pizza", "🍝 slurping spaghetti", "🍦 licking an ice cream", "🍉 spitting seeds", "🥣 stirring a potion",
  "🧁 decorating a cake", "🍽️ setting the table", "🥄 balancing on a spoon", "🧃 drinking through a straw", "🍪 stealing cookies", "🥛 spilling milk", "🥶 shivering", "🥵 sweating",
  "🧹 sweeping", "🧼 washing up", "🛁 having a bath", "🪥 brushing teeth", "🚿 singing in the shower", "👕 folding laundry", "🧺 hanging washing out", "🛏️ making the bed",
  "🪴 gardening", "🌱 planting seeds", "🍎 picking apples", "🌾 harvesting", "🐄 milking a cow", "🐑 herding sheep", "🐕 walking the dog", "🐈 chasing a cat",
  "🧗 abseiling", "🕳️ digging", "⛏️ mining for gold", "🏗️ building", "🔨 hammering", "🪚 sawing", "🔧 fixing", "🧱 stacking bricks",
  "🧩 doing a jigsaw", "🎲 playing a board game", "🃏 playing cards", "🎮 playing video games", "📺 watching TV", "📱 taking a selfie", "📸 taking photos", "🎬 filming a movie",
  "🎸 playing guitar", "🥁 drumming", "🎺 trumpeting", "🎻 fiddling", "🎹 playing piano", "🎵 humming", "🎶 whistling", "📢 shouting",
  "🤫 whispering", "🗣️ telling a joke", "🧙 casting a spell", "🪄 doing magic tricks", "🔮 telling fortunes", "🧞 granting wishes", "🏴‍☠️ burying treasure", "🗺️ following a map",
  "🎁 wrapping presents", "🎂 blowing out candles", "🎈 blowing up balloons", "🎈 popping balloons", "🥳 having a party", "🎅 delivering presents", "🎄 decorating a tree", "⛄ building a snowman",
  "❄️ having a snowball fight", "🏰 building a sandcastle", "🧊 melting", "🌧️ splashing in puddles", "💦 having a water fight", "🫧 blowing bubbles", "🪣 filling a bucket", "🌊 getting splashed",
  "🚗 driving", "🚌 catching the bus", "🚂 chugging along", "🚁 hovering", "🛶 paddling", "🚜 ploughing", "🚒 putting out a fire", "🚓 chasing a robber",
  "🏃 running away", "😨 trembling", "🤸 bouncing", "🦘 hopping", "🐸 leaping", "🐒 swinging", "🦥 hanging upside down", "🐧 waddling",
  "🦆 quacking", "🐔 clucking", "🐮 mooing", "🐷 oinking", "🐺 howling", "🐝 buzzing", "🐍 slithering", "🦖 stomping",
  "🤝 shaking hands", "🤗 hugging", "😘 blowing a kiss", "👋 waving", "👏 clapping", "🙌 high-fiving", "🤞 crossing fingers", "👍 giving a thumbs up",
  "🫠 slipping on a banana skin", "🥴 wobbling", "🤪 pulling silly faces", "😜 sticking out a tongue", "🤓 doing homework", "🧠 thinking hard", "💡 having a bright idea", "🥸 wearing a disguise",
  "🎓 graduating", "👑 wearing a crown", "👗 trying on clothes", "👠 falling off high heels", "💇 getting a haircut", "💅 painting nails", "🧔 shaving", "🪞 looking in a mirror",
  "🛒 pushing a trolley", "💰 counting money", "🔑 losing keys", "📬 posting a letter", "☎️ answering the phone", "💻 typing", "🖨️ photocopying", "⏰ oversleeping",
  "🚽 sitting on the loo", "🧻 unrolling toilet roll", "🍑 wiggling a bum", "🩲 losing underpants", "🧦 pulling on socks", "👟 tying shoelaces", "🥾 stomping in wellies", "🦶 tickling feet"
];
